[versions]
composeBom = "2024.09.00"
composeUi = "1.5.0"
material3 = "1.2.0"
runtimeKtx = "2.9.4"
toolingPreview = "1.5.0"
navigationCompose = "2.8.2"
iconsExtended = "1.1.0"

[libraries]
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "composeUi" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "runtimeKtx" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "toolingPreview" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material.icons", name = "icons-extended", version.ref = "iconsExtended" }
